name: release-please

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_GITHUB_TOKEN }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
        if: ${{ steps.release.outputs.releases_created }}

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
        if: ${{ steps.release.outputs.releases_created }}

      - name: Set node version to 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: pnpm
        if: ${{ steps.release.outputs.releases_created }}

      - name: Install node_modules
        run: pnpm install --frozen-lockfile --prefer-offline
        if: ${{ steps.release.outputs.releases_created }}

      - name: Publish to npm
        run: pnpm publish --no-git-checks --filter "@fuf-stack/*"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        if: ${{ steps.release.outputs.releases_created }}
