name: Release Package

permissions:
  contents: write
  id-token: write

# when vX.X.X tag is created
on:
  push:
    tags:
      - '@fuf-stack/*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Set node version to 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Install node_modules
        run: pnpm install --frozen-lockfile --prefer-offline

      # - name: Build packages
      #   run: pnpm build

      - name: Publish to npm
        run: pnpm publish --no-git-checks --filter ${{ github.ref_name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create github release
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
